### ISSUE TITLE
DPMI?

### ISSUE THREAD

**Issue by stsp** [nabe-abk/free386#1]
`Compatible: MS-DOS and XMS and VCPI (with HIMEM.SYS and EMM386.EXE)`

Just wondering, does your extender support
DPMI, the way pharlap's 386 extender did?

**Comment by nabe-abk** [comment]
Free386 do not support DPMI.
There are various versions of RUN386(Pharlap's Extender), 
do not support DPMI probably on old version. (Ver1.2 and other)

**Comment by stsp** [comment]
Thanks for the info.
Are there the plans to add DPMI in
the future, as well as the compatibility
with the RUN286 extender?
There is some demand for that within
my project, dosemu2. dosemu2 only
supports DPMI for protected-mode
programs, so run386/DPMI works
perfectly, but run286 - not.
Maybe if you happen to have some
info on the run286 API, I could even
implement that myself.

**Comment by nabe-abk** [comment]
I do not use RUN286 and do not have it.
There is no update plan including DPMI support.

**Comment by stsp** [comment]
OK, thanks.
