### ISSUE TITLE
"Expection Interrupted : INT 0Eh - Page Fault" on PC-9821

### ISSUE THREAD

**Issue by aluminaceramix** [nabe-abk/free386#2]
Environment:
PC-9821As2/U2(i486DX2-66MHz Equipmented) Memory 24MB
MS-DOS 5.0A-H(Bundled), himem.sys, emm386.exe(patched)
MS-DOS 5.0A-H(bundled), melemm.386
MS-DOS 5.0A-H(bundled), himem.sys(Win98), emm386.exe(Win98)

Likely message displayed in above environments.

Command:
A>free386.com [Return]
A>free386.com alink-p1.exp [Return]

*Same* message displayed in above commands.

Message: (melemm.386)
Free386(386|DOS-Extender) for PC-9801/9821 Ver0.63 2020/07/27 (C)nabe@abk
------------------------------------------------------------------
Expection Interrupted : INT 0Eh - Page Fault                      
Err = FFFF_0002  CS:EIP = 0008:0000_0C8C   SS:ESP = 0010:0000_FDB0
 DS = 0010        ES = 0040        FS = 0010        GS = 0010
EAX = 0000_0000  EBX = 0000_4144  ECX = 0000_0400  EDX = 0040_0007
ESI = 0040_0000  EDI = 0100_0000  EBP = 0000_1000  FLG = 0001_3246
CR0 = 8000_0033  CR2 = 0100_0000  CR3 = 0001_7000  O0 D1 S1 Z0 C0 
------------------------------------------------------------------

Message: (melemm.386 with reduced config.sys)
Free386(386|DOS-Extender) for PC-9801/9821 Ver0.63 2020/07/27 (C)nabe@abk
------------------------------------------------------------------
Expection Interrupted : INT 0Eh - Page Fault                      
Err = 6106_0002  CS:EIP = 0008:0000_0C8C   SS:ESP = 0010:0000_FDB0
 DS = 0010        ES = 0040        FS = 0010        GS = 0010
EAX = 0000_0000  EBX = 0000_4FD4  ECX = 0000_0400  EDX = 0040_0007
ESI = 0040_0000  EDI = 005F_0000  EBP = 0000_1000  FLG = 0001_3246
CR0 = 8000_0033  CR2 = 005F_0000  CR3 = 0000_F000  O0 D1 S1 Z0 C0 
------------------------------------------------------------------

**Comment by nabe-abk** [comment]
- Which "free386" binary did you choose?
- Are you read "/doc-ja/PC98.txt" ?
- Will you test with "vem486.sys".

**Comment by aluminaceramix** [comment]
MSG> Free386(386|DOS-Extender) for PC-9801/9821 Ver0.63 
I used for PC-98 version of free386.com
I was read /doc-ja/PC98.txt, emm386.exe patch info used from this document.
Tested with vem486, unchange behavior.

**Comment by nabe-abk** [comment]
I test PC-98 binary of "free386.com" on FM-TOWNS(emu) and PC/AT(vm) it worked fine.
You will check BIOS setting or other setting.
And you will test with remove the extended memory.

**Comment by aluminaceramix** [comment]
Tested in under<=16MB of extended memory.
Both BIOS setting disconnect/use 16MB System Area.
unchanged behavior.

Tested in xnp21 emulator in FreeBSD.
disk cache utility dkc.exe
ram disk utility crd.exe
above both utilities in config.sys, then "INT 0Eh Page Fault".
remove the either utility, work well the free386.com.

But both utilities in config.sys, work well the command "exe386.exe nasm.exp".

Thanks for testing.

**Comment by aluminaceramix** [comment]
More tested.
disk cache utility dkc.exe
ram disk utility crd.exe
Both utilities resident in main memory, not umb, work well the free386.com.

Thanks.

**Comment by nabe-abk** [comment]
Please tell me message from "free386.com" with "-v" option, when "INT 0Eh - Page Fault".
Probably failing to get memory capacity.

**Comment by aluminaceramix** [comment]
> Please tell me message from "free386.com" with "-v" option, when "INT 0Eh - Page
 Fault".
> Probably failing to get memory capacity.

xnp21 PC-98 Emulator's result.

Free386(386|DOS-Extender) for PC-9801/9821 Ver0.63 2020/07/27 (C)nabe@abk
Found XMS 3.0
[VCPI] Physical Memory size =  14336 KB
[XMS]  Allocate Ext  Memory =   8112 KB (0061_4000h)
[DOS]  Allocate Real Memory =     16 KB (0002_2000h) + 4KB(fragment)
[DOS]  Call Buffer Memory   =      4 KB (0002_0350h)
[DOS]  Free386.com Memory   =     64 KB (0001_0340h)
------------------------------------------------------------------
Expection Interrupted : INT 0Eh - Page Fault                      
Err = 0000_0002  CS:EIP = 0008:0000_0C8C   SS:ESP = 0010:0000_FDB0
 DS = 0010        ES = 0040        FS = 0010        GS = 0010
EAX = 0000_0000  EBX = 0000_4CC4  ECX = 0000_0400  EDX = 0040_0007
ESI = 0040_0000  EDI = 0061_4000  EBP = 0000_1000  FLG = 0000_3246
CR0 = E000_002D  CR2 = 0061_4000  CR3 = 0001_5000  O0 D1 S1 Z0 C0 
------------------------------------------------------------------

**Comment by nabe-abk** [comment]
Thank you test. I found bug in free386.com.
If used XMS memory over 4MB by other programs, occur this error.

**Comment by nabe-abk** [comment]
I am fix PAGE TABLE bug.
Please test version 0.63 binary.

**Comment by nabe-abk** [comment]
I am fix PAGE TABLE bug.
Please test version 0.64 binary.

**Comment by aluminaceramix** [comment]
Work well the version 0.64 of the free386.com.
Thank you.
