### ISSUE TITLE
Support non VCPI enviroment (and non XMS on TownsOS)

### ISSUE THREAD

**Issue by captainys** [nabe-abk/free386#4]
nabeさん、

津軽その他作ってる山川です。現在、FM TOWNS用に互換ROMは既にあるので、あとはIO.SYS, TBIOSなどを書けばフリーゲームを実行可能な状態で再配布したり、ゲームの復刻版の発売などが可能になると思い、Free TOWNS OSプロジェクトなるものを始めました。https://github.com/captainys/FreeTOWNSOS ←ここです。現在、ORICONでコマンドが動いて、Towns OS V1.1 L30のTBIOS.SYSを使ってTBIOS.BINをロードできて、RUN386.EXEでコンソールアプリなら起動できるところまでできました。

今後TBIOSは自作TBIOSで置き換えるとして、DOS ExtenderにはnabeさんのFree386を使用させていただこうと思っていたのですが、XMSとEMSが必要とのことで、さすがにこのふたつまで書くのは現実的では無くて、互換DOSだとFreeDOSのJEMM386.EXEなどへの対応も難しいのですが、Free386をXMS無し, EMS無し環境に対応させるのはどのぐらい難しいでしょうか?

**Comment by nabe-abk** [comment]
Free386側を書き換えても大したことないとは思いますが、Free386が動く程度のXMS/VCPIを実装するのも同じぐらいの難易度だと思います。

どちらにしろ、TOWNSのIO.SYSにはXMS相当の機能がありますし（[Inside TOWNS-OS](https://www.purose.net/befis/download/ito/)の[TOS.SYS.TXT](https://www.purose.net/befis/download/ito/tos.sys.txt)参照）、HIMEM.SYSなら、[他から移植](https://github.com/Baron-von-Riedesel/HimemX)してもA20ライン操作ぐらいしか機種依存しなそうなので難しくなさそう（多分）。

また、Free386を動かす程度のVCPIを実装するなら仮想86モード（+EMS）は不要ですので、それこそ全く難しくないです。

問題はFree386が動く程度のXMS/VCPIを、DOSアプリが本物と勘違いする可能性があることですが、ゲームとか用なら問題ないかと思います。Free386専用XMS/VCPI判別法（存在確認の戻り値を少しだけ変えるとか）を用意すればそこも完璧かなと思います。

**Comment by captainys** [comment]
お返事ありがとうございます！
なるほど。僕もその後Free386のソースを読ませていただいて、自力VCPIの可能性を模索していたところでしたが、やってみます。issueとは違いますが、質問などが発生したらここで聞いてしまっても良いでしょうか？

**Comment by nabe-abk** [comment]
構わないですよ。Issue開けておきますので、どうぞ。

**Comment by captainys** [comment]
ありがとうございます！早速お言葉に甘えてなんですが、.... 計算間違ってました。すみません、無視してください。

**Comment by nabe-abk** [comment]
VCPIなし環境はいまちょっとFree386側をいじってみてるので（完成まで行けるかは不明）、念のためXMSドライバ作りを先にやったほうが良いかも……。

**Comment by captainys** [comment]
ありがとうございます！僕は、実はVCPIとXMSの区別がわかってないというレベルなのですが、他に同時に走ってるアプリは無い前提で、上位メモリは全部Free386用にロックしたことにして、Free386が使ってるシステムコールだけ実装してみたら、とりあえずFree386がプロテクテドモードに入るところまでこぎつけて、プロテクテドモードからVCPIのコールバックに入ってくる(現在そこで止めてる)ことまで確認したので、次、リアルモード←→プロテクテドモードの行き来を書いてみます。  こんな感じでやってみてます。 https://github.com/captainys/FreeTOWNSOS/blob/master/src/MINVCPI.NSM

見た感じ、Free386は取れるだけの上位メモリを取ってしまって、あとはプロテクテドモード←→リアルモードの行き来にだけVCPI/XMSを使っているのかと思ったのですが、大体合ってますかね？

**Comment by nabe-abk** [comment]
XMS/VCPI は [doc-ja/dos/](https://github.com/nabe-abk/free386/tree/main/doc-ja/dos) にそれぞれ説明がありますので軽く目を通せばわかるかと。特に xms30j.txt の後半。

> 取れるだけの上位メモリを取ってしまって、あとはプロテクテドモード←→リアルモードの行き来にだけVCPI/XMSを使っているのか

メモリ取得に使っているのがXMSで、CPUモード変更に使っているのがVCPIですが、だいたいあってます。

**Comment by captainys** [comment]
ありがとうございます！とりあえず、上のMINVCPI.SYSでコンソールEXPアプリ(単に一行printfするだけですが)の起動と終了に成功しました！画面にゴミが発生するのですが、多分これは僕がC0000h～FFFFFFh付近を放置してあるので、そこをなんとかすれば出なくなるのではないか、と見ています。(なんかコンソールにPage Tableみたいなのが見える)

多分このまま何事もなく無事EXPが実行できるようになるほど甘くは無さそうなので、引き続き、詰まったとき質問させてください。

**Comment by captainys** [comment]
現在互換TBIOS (TGBIOS)を開発中ですが、今のところテストプログラムなど、Free386 + MINVCPI.SYSで完璧に動作しています。さすがです！DOS-Extenderから作らなければならないことになったら多分心が折れてました。今のところ互換TBIOSはTowns OS V1.1のようにリアルメモリに置いているのですが、リアルモードプログラムの実行はあまり考えていないものの、そのうち1MBより上のメモリに置こうと思っていて、そのとき多分追加で質問が発生すると思うので、もう少しこのissue開けておいてください。よろしくお願いします。

**Comment by nabe-abk** [comment]
Ver1.00をリリースしました。
VCPIなし環境（TownsOSにおいてXMS/VCPIなし環境）に対応しましたので、このissueは閉じさせていただきます。

代わりにそちらにissueを立てました。
[https://github.com/captainys/FreeTOWNSOS/issues/6](https://github.com/captainys/FreeTOWNSOS/issues/6)
