### ISSUE TITLE
Free386 on TOWNS Real-Mode RAM/ROM change on start32

### ISSUE THREAD

**Issue by captainys** [nabe-abk/free386#5]
Non-VCPI環境への対応ありがとうございます。こちらでも試してみました。
MINVCPI.SYSのINT 67Hを削ってXMSのふりをする部分だけ残したところ、小さなEXPファイルは問題なく実行できたのですが、D0000h付近を使う場合クラッシュするようです。(Panic Ballで発生)
TOWNSのDOS-Extenderはプロテクテドモードに入るときC0000h～FFFFFhのRAM/ROMマッピングを全部RAMに切り替えて、リアルモードに出るときROMとVRAMに切り替えているようです。
この問題はとりあえずMINVCPI.SYS内でINT 67H AX=DE0CHが入ってきたとき切り替えて対応していたのですが、free386側で、use_vcpiが0 (VCPIドライバが入ってないので多分Towns OS V2.1L31以下)のときは、プロテクテドモードに切り替える前にI/O 404Hと480Hを保存した上で全部RAMにして、リアルモードに戻ってくるときにリストアするような処理を追加するのは可能でしょうか?

**Comment by nabe-abk** [comment]
メモリマネージャーが「そこにメモリがある」と返すなら、それを信じるのは通常の挙動だと思います。そこにメモリがあることが保証できないのならば、メモリマネージャーは「C0000-FFFFFh」を空きメモリとして返すべきではありません。

RUN386も確認しましたけど、C0000h-FFFFFhは空きメモリとしては使用していません。セレクタ40hに貼り付けてはいますが。

**Comment by captainys** [comment]
なんと、TOWNS OSってC0000h-FFFFFh使ってなかったでしたっけ? と、思って試しにTowns OS V2.1 L31で試したら、たしかにC0000～避けてますね。256KB使ってなかったのか。Towns MENUが動いてるとき000C:*で止めたらC0000-FFFFFはRAMになってるので当然使ってるもんだと思ったら、使ってなかったですね。それだと、Fake XMSドライバの方でC0000-FFFFFを使用可能と返さないように書き換えてみます。ありがとうございます。
