### ISSUE TITLE
init_CoCo and init_coco mix up

### ISSUE THREAD

**Issue by captainys** [nabe-abk/free386#7]
たびたびすみません、pc_towns.asmの中に、

proc2 init_CoCo

というラベルと、

init_coco	db	0

というラベルがあって、フラグは小文字のinit_cocoを使うようになってるようなのですが、3か所で、

Line 125  mov	b [init_CoCo], 1
Line 199  cmp	b [init_CoCo], 0
Line 606  cmp	b [init_CoCo], 0

と、大文字になっているため、COCOが常駐していない状態でもwakeup_nsddが呼ばれてしまう現象が起きてます。INT 8EH AX=C103HがAH!=0を返す限りは問題は発生しませんが、一応、バグのようなので報告しました。

**Comment by nabe-abk** [comment]
バグ報告、ありがとうございます。
修正しました。
